- name: Install promtail
  ansible.builtin.apt:
    deb: "{{ promtail_package_url }}"
    state: present
  tags: promtail

- name: Install acl
  ansible.builtin.apt:
    name: acl
    state: present
  tags: promtail

- name: Start and enable promtail service
  ansible.builtin.systemd:
    name: promtail
    state: started
    enabled: yes
  tags: promtail
  
