---
# vars file for promtail
promtail_version: 3.2.1
promtail_package_url: https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail_{{ promtail_version }}_amd64.deb
promtail_loki_server: http://localhost:3100/loki/api/v1/push
promtail_scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: messages
          __path__: /var/log/syslog
      - targets:
          - localhost
        labels:
          job: auth
          __path__: /var/log/auth.log
  - job_name: nginxlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: applogs
          __path__: /var/log/applications/nginx/*.log
