---
# tasks file for users

- name: Ensure all group exists
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ users_monad_groups }}"
  tags: base, users

- name: Create monad users
  ansible.builtin.user:
    name: "{{ item.name }}"
    create_home: yes
    group: "{{ item.group }}"
    password_lock: false
    shell: /bin/bash
    password: "{{ 'secure_password' | password_hash('sha512') }}"  
  loop: "{{ users_monad }}"
  tags: base, users

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: '0700'
  loop: "{{ users_monad }}"
  tags: base, users

- name: Install public SSH keys
  ansible.builtin.copy:
    content: "{{ item.ssh_key }}"
    dest: "/home/{{ item.name }}/.ssh/authorized_keys"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: '0600'
  loop: "{{ users_monad }}"
  tags: base, users

- name: Grant permissions per group
  community.general.sudoers:
    name: "{{ item.group }}-sudoers"
    state: present
    group: "{{ item.group }}"
    nopassword: true
    commands: "{{ item.commands }}"
  loop: "{{ users_group_sudoers }}"
  tags: base, sudoers
