- name: Install nginx package
  ansible.builtin.package:
    name: nginx
    state: present
  tags: install

- name: Recursibly grant nginx user to root folder
  ansible.builtin.file:
    path: "{{ nginx_root_folder }}"
    state: directory
    mode: '0755'
  tags: install

- name: Create custom log directory for Nginx
  ansible.builtin.file:
    path: "{{ nginx_log_dir }}"
    state: directory
    mode: '0755'
  tags: install

- name: Allow all access to tcp port {{ nginx_port }}
  community.general.ufw:
    rule: allow
    port: "{{ nginx_port }}"
    proto: tcp
  tags: install

- name: Deploys default site
  ansible.builtin.copy:
    src: files/index.html
    dest: "{{ nginx_root_folder }}"
    mode: '0644'
  tags: 
    - install

- name: Set up Nginx default site
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx
  tags: 
    - install

- name: Set up Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx
  tags: 
    - install
    - configure

- name: Start and enable Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
  tags: install




