- name: Install ubuntu packages
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: base

- name: Allow traffic to common ports 
  community.general.ufw:
    rule: allow
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
  loop: "{{ base_firewall_ports }}"
  tags: firewall

- name: Limit ssh connections
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
  tags: firewall

- name: Set ufw logging
  community.general.ufw:
    logging: 'on'
  tags: firewall

- name: Enables ufw 
  community.general.ufw:
    state: enabled
  tags: firewall

- name: Configures sshd 
  ansible.builtin.template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart ssh
  tags: sshd
